spring:
  datasource:
    username: postgres
    password: postgrespw
    url: jdbc:postgresql://localhost:5432/urms
  jpa:
    open-in-view: false
  liquibase:
    enabled: true
    default-schema: public
    change-log: classpath:/migrations/changelogs/db-changelog-master.xml
logging:
  level:
    org.springframework.security: trace
jwt:
  token-key: '{"kty":"oct","k":"h17SGRX5FRZooHA0RKGctZ-KtR9FoESgCnHG3BNg5XI"}'
